version = 1

exclude_patterns = [
  "/cuBLAS/Level-2/hpmv/**",
  "/cuBLAS/Extensions/Nrm2Ex/**",
  "/cuBLAS/Level-2/spr/**",
  "/cuSPARSELt/matmul_minimal/**",
  "/cuSOLVER/Xsyevd/**",
  "/cuSOLVER/Xgeqrf/**",
  "/cuFFTMp/JAX_FFT/src/fft_common/**",
  "/cuBLAS/Extensions/GemmStridedBatchedEx/**",
  "/nvTIFF/**",
  "/cuBLAS/Extensions/Csyrk3mEx/**",
  "/nvJPEG2000/nvJPEG2000-Decoder/images/**",
  "/nvJPEG2000/nvJPEG2000-Encoder/**",
  "/cuSOLVER/Xsyevdx/**",
  "/cuBLAS/Level-3/herk/**",
  "/cuTENSOR/python/cutensor/torch/**",
  "/cuTENSOR/python/cutensor/**",
  "/cuBLAS/Level-3/trmm/**",
  "/cuSOLVER/Xtrtri/**",
  "/cuBLAS/Level-3/gemmBatched/**",
  "/MathDx/cuFFTDx/convolution/**",
  "/cuSOLVER/sygvd/**",
  "/cuRAND/Host/sobol64/**",
  "/cuSPARSE/spsv_csr/**",
  "/cuFFTMp/Fortran_samples/r2c_c2r_shared_scratch/**",
  "/cuBLAS/Extensions/ScalEx/**",
  "/cuSPARSE/dense2sparse_csr/**",
  "/cuBLAS/Level-3/**",
  "/cuBLAS/Level-2/trmv/**",
  "/cuFFTMp/JAX_FFT/tests/**",
  "/cuFFTMp/samples/c2c/**",
  "/cuSPARSE/spgemm_alg2/**",
  "/cuBLAS/Extensions/GemmEx/**",
  "/cuBLAS/Level-1/**",
  "/MathDx/cuFFTDx/utils/**",
  "/cuBLAS/Level-2/tbsv/**",
  "/cuSPARSE/spmm_csr_batched/**",
  "/cuSPARSE/spsm_coo/**",
  "/cuFFT/3d_mgpu_r2c_c2r/**",
  "/MathDx/**",
  "/cuBLAS/Level-2/gbmv/**",
  "/NPP/distanceTransform/**",
  "/cuSPARSE/spmm_coo/**",
  "/cuFFTMp/Fortran_samples/r2c_c2r/**",
  "/cuFFTMp/extra_bootstraps/**",
  "/NPP/batchedLabelMarkersAndCompression/images/**",
  "/cuSOLVER/Xgesvd/**",
  "/cuTENSOR/**",
  "/cuBLAS/Level-2/hemv/**",
  "/nvJPEG/Image-Resize/**",
  "/cuBLAS/Level-1/amin/**",
  "/nvJPEG/nvJPEG-Decoder/**",
  "/cuBLAS/Level-1/scal/**",
  "/cuSPARSE/dense2sparse_blockedell/**",
  "/cuSOLVER/utils/**",
  "/cuSOLVER/Xgesvdr/**",
  "/nvJPEG2000/nvJPEG2000-Decoder/images/2k_image_lossless/**",
  "/cuSOLVERMp/**",
  "/cuBLAS/Level-2/spmv/**",
  "/cuBLAS/Level-2/her2/**",
  "/cuFFTMp/Fortran_samples/c2c/**",
  "/cuFFTMp/samples/r2c_c2r_no_descriptors/**",
  "/cuFFTMp/JAX_FFT/src/cufftmp_jax/lib/**",
  "/cuBLAS/Level-1/rotg/**",
  "/cuBLAS/Level-3/trsmBatched/**",
  "/cuBLASLt/LtPlanarComplex/**",
  "/cuSPARSE/sddmm_csr_batched/**",
  "/cuBLAS/Level-1/axpy/**",
  "/nvTIFF/nvTIFF-Decode-Encode/**",
  "/cuSPARSELt/**",
  "/.vscode/**",
  "/cuBLAS/Level-2/syr/**",
  "/cuRAND/Host/philox/**",
  "/cuRAND/Host/sobol32/**",
  "/cuRAND/Host/xorwow/**",
  "/cuFFTMp/Fortran_samples/Fortran_wrappers_nvhpc/**",
  "/cuBLAS/**",
  "/cuFFTMp/Fortran_samples/**",
  "/cuSOLVER/syevjBatched/**",
  "/cuBLAS/Level-1/rotmg/**",
  "/cuBLASLt/LtSgemmSimpleAutoTuning/**",
  "/cuFFTMp/Fortran_samples/c2c_pencils/**",
  "/cuBLAS/Level-3/her2k/**",
  "/cuBLAS/Extensions/Cherk3mEx/**",
  "/cuSOLVER/getrf/**",
  "/cuSOLVER/MgSyevd/**",
  "/cuSPARSE/spgemm/**",
  "/nvJPEG2000/nvJPEG2000-Decoder/images/4k_image_lossy/**",
  "/cuSOLVER/orgqr/**",
  "/nvJPEG2000/nvJPEG2000-Decoder-Tile-Partial/**",
  "/cuBLAS/Level-2/tbmv/**",
  "/cuSPARSE/scatter/**",
  "/cuSOLVER/syevj/**",
  "/cuFFTMp/samples/r2c_c2r_shared_scratch/**",
  "/cuBLAS/Level-2/sbmv/**",
  "/cuBLAS/Level-3/trsm/**",
  "/cuBLAS/Level-1/amax/**",
  "/cuBLAS/Level-3/syrkx/**",
  "/cuBLAS/Level-2/syr2/**",
  "/cuSPARSE/spsm_csr/**",
  "/cuBLAS/Level-3/gemmStridedBatched/**",
  "/cuFFTMp/samples/r2c_c2r/**",
  "/nvJPEG2000/nvJPEG2000-Decoder/images/2k_image_lossy/**",
  "/cuFFTMp/JAX_FFT/**",
  "/nvJPEG/nvJPEG-Decoder/input_images/**",
  "/cuSOLVER/gesvdaStridedBatched/**",
  "/cuSOLVER/gesvdjBatched/**",
  "/cuFFTMp/samples/reshape/**",
  "/cuSOLVER/MgPotrf/**",
  "/cuSPARSELt/matmul_advanced/**",
  "/MathDx/cuFFTDx/fft_2d/**",
  "/cuBLASLt/LtDgemmPresetAlgo/**",
  "/cuSPARSE/gpsvInterleavedBatch/**",
  "/nvJPEG2000/nvJPEG2000-Encoder/images/**",
  "/cuRAND/utils/**",
  "/cuBLAS/Extensions/RotEx/**",
  "/NPP/findContour/**",
  "/cuSOLVER/sygvdx/**",
  "/cuBLASLt/LtIgemmTensor/**",
  "/cuFFT/2d_c2r/**",
  "/cuBLAS/Level-1/rot/**",
  "/MathDx/cuFFTDx/block_fft/**",
  "/nvJPEG2000/**",
  "/cuSOLVER/MgGetrf/**",
  "/cuFFT/3d_c2c/**",
  "/NPP/findContour/images/**",
  "/cuBLAS/Level-2/her/**",
  "/cuSOLVER/csrqr/**",
  "/cuBLAS/Level-2/symv/**",
  "/cuSOLVER/cmake/**",
  "/cuBLAS/Level-1/swap/**",
  "/cuTENSORMg/**",
  "/cuFFTMp/JAX_FFT/src/**",
  "/cuSPARSE/spmv_csr/**",
  "/nvJPEG/Image-Resize/input_images/**",
  "/cuBLASLt/LtHSHgemmStridedBatchSimple/**",
  "/cuSOLVER/Xpotrf/**",
  "/cuBLAS/Level-3/syrk/**",
  "/cuSPARSE/gather/**",
  "/cuSPARSE/sddmm_csr/**",
  "/cuFFTMp/samples/**",
  "/cuSPARSE/spmv_coo/**",
  "/cuSPARSE/graph_capture/**",
  "/cuBLAS/Level-3/herkx/**",
  "/cuBLAS/Extensions/CsyrkEx/**",
  "/NPP/watershedSegmentation/images/**",
  "/cuSPARSE/spgemm_mem/**",
  "/cuSPARSE/**",
  "/cuSOLVER/**",
  "/nvJPEG2000/nvJPEG2000-Decoder-Pipelined/**",
  "/cuSPARSE/cg/**",
  "/cuBLAS/Level-2/hbmv/**",
  "/cuRAND/Host/mtgp32/**",
  "/cuBLAS/Extensions/tpttr/**",
  "/cuBLASLt/LtSgemm/**",
  "/NPP/**",
  "/cuFFTMp/samples/c2c_no_descriptors/**",
  "/cuSOLVER/gesvdj/**",
  "/.git/**",
  "/cuBLAS/Level-3/syr2k/**",
  "/nvJPEG/**",
  "/cuBLAS/utils/**",
  "/cuBLAS/Extensions/geam/**",
  "/cuFFT/1d_c2c/**",
  "/cuFFT/1d_r2c/**",
  "/cuRAND/cmake/**",
  "/cuFFTMp/JAX_FFT/misc/**",
  "/cuBLAS/Level-2/trsv/**",
  "/cuBLAS/Level-2/tpsv/**",
  "/cuSPARSE/compression/**",
  "/cuSOLVER/sygvj/**",
  "/cuBLAS/Level-1/nrm2/**",
  "/MathDx/cuFFTDx/**",
  "/cuBLAS/Level-1/copy/**",
  "/cuBLAS/Level-3/gemm3m/**",
  "/MathDx/cuFFTDx/fft_3d/**",
  "/cuRAND/Host/mrg32k3a/**",
  "/nvTIFF/nvTIFF-Decode-Encode/images/**",
  "/cuTENSOR/python/cutensor/tensorflow/**",
  "/cuRAND/Host/mt19937/**",
  "/cuBLASLt/LtSgemmCustomFind/**",
  "/cuSPARSE/axpby/**",
  "/cuBLAS/Level-3/symm/**",
  "/cuSOLVER/Xgesvdp/**",
  "/cuBLAS/Level-1/dot/**",
  "/cuSPARSE/spgemm_reuse/**",
  "/cuBLAS/Extensions/GemmBatchedEx/**",
  "/cuSPARSELt/matmul_minimal_playground/**",
  "/cuBLAS/Level-2/**",
  "/nvJPEG/nvJPEG-Decoder-Backend-ROI/**",
  "/NPP/watershedSegmentation/**",
  "/cuSOLVER/Xgetrf/**",
  "/nvJPEG/nvJPEG-Decoder-MultipleInstances/**",
  "/cuSOLVER/potrfBatched/**",
  "/cuSPARSE/spmm_csr_op/**",
  "/**",
  "/cuBLAS/cmake/**",
  "/cuFFTMp/Fortran_samples/reshape/**",
  "/cuFFTMp/samples/iterators/**",
  "/cuSPARSELt/matmul/**",
  "/nvJPEG2000/nvJPEG2000-Decoder/**",
  "/cuBLAS/Extensions/**",
  "/cuBLAS/Level-1/asum/**",
  "/cuFFTMp/samples/r2c_c2r_pencils/**",
  "/cuFFTMp/samples/c2c_pencils/**",
  "/cuBLAS/Extensions/CherkEx/**",
  "/cuSPARSE/sparse2dense_csr/**",
  "/cuRAND/Host/scrambled_sobol32/**",
  "/cuFFTMp/Fortran_samples/r2c_c2r_pencils/**",
  "/cuFFTMp/JAX_FFT/src/xfft/**",
  "/nvJPEG/nvJPEG-Decoder-Backend-ROI/input_images/**",
  "/cuBLAS/Level-2/hpr/**",
  "/cuBLAS/Level-3/hemm/**",
  "/cuSPARSE/spvv/**",
  "/cuSOLVER/gesvd/**",
  "/cuSPARSE/spmm_csr/**",
  "/cuSOLVER/gesv/**",
  "/cuSPARSE/spsv_coo/**",
  "/NPP/batchedLabelMarkersAndCompression/**",
  "/cuSOLVER/syevdx/**",
  "/cuFFT/3d_mgpu_c2c/**",
  "/cuFFTMp/JAX_FFT/src/cufftmp_jax/**",
  "/cuRAND/Host/scrambled_sobol64/**",
  "/cuSOLVER/ormqr/**",
  "/cuFFTMp/samples/common/**",
  "/cuTENSOR/python/**",
  "/cuFFT/**",
  "/cuRAND/Host/**",
  "/cuBLAS/Extensions/DotEx/**",
  "/cuSOLVER/syevd/**",
  "/cuBLASLt/**",
  "/cuBLAS/Extensions/AxpyEx/**",
  "/cuSPARSE/spmm_coo_batched/**",
  "/MathDx/cuFFTDx/helloworld/**",
  "/nvTIFF/nvTIFF-Python-Example/**",
  "/cuBLAS/Extensions/dgmm/**",
  "/cuBLAS/Level-2/tpmv/**",
  "/cuFFT/utils/**",
  "/cuBLAS/Level-2/ger/**",
  "/cuBLASLt/Common/**",
  "/cuSPARSE/bicgstab/**",
  "/cuSPARSE/spmm_blockedell/**",
  "/cuRAND/**",
  "/NPP/distanceTransform/images/**",
  "/cuSPARSE/rot/**",
  "/cuBLAS/Extensions/trttp/**",
  "/cuFFTMp/**",
  "/cuBLAS/Level-1/rotm/**",
  "/nvTIFF/nvTIFF-Python-Example/nvTIFF-Python-Whl/**",
  "/cuBLAS/Level-2/hpr2/**",
  "/nvJPEG/Image-Resize-WaterMark/**",
  "/cuBLASLt/LtFp8Matmul/**",
  "/cuBLAS/Level-2/gemv/**",
  "/cuBLAS/Level-3/gemm/**",
  "/cuFFT/1d_mgpu_c2c/**",
  "/cuSPARSE/coosort/**",
  "/cuBLAS/Level-2/spr2/**",
  "/nvJPEG/Image-Resize-WaterMark/input_images/**",
  "/cuSPARSELt/matmul_bench/**"
]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "cxx"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "black"

[[transformers]]
name = "autopep8"