version = 1

exclude_patterns = [
  "/cuSOLVER/syevd/**",
  "/MathDx/cuFFTDx/fft_2d/**",
  "/nvTIFF/nvTIFF-Decode-Encode/cudamacro.h",
  "/nvTIFF/nvTIFF-Decode-Encode/CMakeLists.txt",
  "/nvTIFF/nvTIFF-Decode-Encode/README.md",
  "/nvTIFF/nvTIFF-Decode-Encode/nvTiff_utils.h",
  "/nvTIFF/nvTIFF-Decode-Encode/getopt.h",
  "/nvTIFF/nvTIFF-Decode-Encode/nvTiff_utils.cpp",
  "/nvTIFF/nvTIFF-Decode-Encode/nvtiff_example.cu",
  "/cuSPARSE/spmm_csr/**",
  "/cuTENSOR/python/cutensor/torch/**",
  "/cuSPARSE/scatter/**",
  "/cuSOLVER/MgGetrf/**",
  "/cuBLAS/Level-3/symm/**",
  "/cuSOLVER/syevj/**",
  "/cuFFTMp/extra_bootstraps/**",
  "/cuSOLVER/sygvdx/**",
  "/cuBLAS/Level-2/trmv/**",
  "/cuSOLVER/gesvd/**",
  "/cuSPARSE/sddmm_csr_batched/**",
  "/cuSPARSELt/matmul_minimal_playground/**",
  "/cuBLAS/README.md",
  "/cuBLAS/Level-1/scal/**",
  "/cuRAND/Host/sobol32/**",
  "/cuSPARSELt/matmul/**",
  "/cuBLAS/Level-3/trmm/**",
  "/cuFFTMp/samples/common.mk",
  "/cuBLAS/Level-1/amax/**",
  "/cuBLAS/Level-1/rot/**",
  "/NPP/distanceTransform/CMakeLists.txt",
  "/NPP/distanceTransform/README.md",
  "/NPP/distanceTransform/distanceTransform.cpp",
  "/NPP/distanceTransform/DistanceTransformTrue_Dolphin1_319x319_16u.jpg",
  "/NPP/distanceTransform/dolphin1_Input_319x319_8u.jpg",
  "/cuBLAS/Level-2/her/**",
  "/MathDx/cuFFTDx/block_fft/**",
  "/nvJPEG/README.md",
  "/cuBLAS/Level-1/dot/**",
  "/cuSPARSE/spsm_coo/**",
  "/cuSOLVER/getrf/**",
  "/cuBLAS/Level-2/hbmv/**",
  "/cuBLAS/Level-3/gemm/**",
  "/cuBLAS/Level-2/spr2/**",
  "/cuBLASLt/CMakeLists.txt",
  "/cuBLASLt/README.md",
  "/cuSOLVER/gesvdj/**",
  "/cuFFTMp/JAX_FFT/tests/**",
  "/cuBLASLt/LtSgemmCustomFind/**",
  "/cuFFTMp/JAX_FFT/misc/**",
  "/cuBLAS/Extensions/ScalEx/**",
  "/nvJPEG/nvJPEG-Decoder-Backend-ROI/CMakeLists.txt",
  "/nvJPEG/nvJPEG-Decoder-Backend-ROI/nvJPEGROIDecode.cpp",
  "/nvJPEG/nvJPEG-Decoder-Backend-ROI/nvJPEGROIDecode.h",
  "/nvJPEG/nvJPEG-Decoder-Backend-ROI/img9_roi.png",
  "/nvJPEG/nvJPEG-Decoder-Backend-ROI/README.md",
  "/nvJPEG/nvJPEG-Decoder-Backend-ROI/threadpool.h",
  "/cuFFTMp/Fortran_samples/c2c_pencils/**",
  "/cuBLAS/Level-2/ger/**",
  "/MathDx/cuFFTDx/utils/**",
  "/cuSOLVER/cmake/**",
  "/cuBLAS/Level-2/syr/**",
  "/cuBLAS/Level-3/trsm/**",
  "/cuSPARSE/spmv_csr/**",
  "/cuBLAS/Level-2/sbmv/**",
  "/NPP/batchedLabelMarkersAndCompression/CMakeLists.txt",
  "/NPP/batchedLabelMarkersAndCompression/batchedLabelMarkersAndCompression.h",
  "/NPP/batchedLabelMarkersAndCompression/batchedLabelMarkersAndCompression.cpp",
  "/NPP/batchedLabelMarkersAndCompression/README.md",
  "/NPP/batchedLabelMarkersAndCompression/dirent.h",
  "/cuBLASLt/LtSgemm/**",
  "/cuBLASLt/LtHSHgemmStridedBatchSimple/**",
  "/cuBLAS/Level-2/hpmv/**",
  "/cuRAND/Host/philox/**",
  "/nvJPEG2000/nvJPEG2000-Decoder-Tile-Partial/**",
  "/cuBLAS/Level-2/tpsv/**",
  "/cuFFTMp/samples/c2c_no_descriptors/**",
  "/cuSPARSE/gather/**",
  "/cuTENSOR/python/cutensor/c_extensions.py",
  "/cuTENSOR/python/cutensor/package_info.py",
  "/cuTENSOR/python/cutensor/__init__.py",
  "/cuTENSOR/python/cutensor/c_extensions_utils.py",
  "/cuTENSOR/python/cutensor/common.py",
  "/NPP/watershedSegmentation/watershedSegmentation.cpp",
  "/NPP/watershedSegmentation/CMakeLists.txt",
  "/NPP/watershedSegmentation/README.md",
  "/NPP/watershedSegmentation/watershedSegmentation.h",
  "/cuFFTMp/Fortran_samples/r2c_c2r/**",
  "/cuBLAS/Level-1/rotmg/**",
  "/cuBLAS/Level-1/axpy/**",
  "/cuSPARSE/spmm_csr_op/**",
  "/cuFFTMp/samples/iterators/**",
  "/cuSOLVER/Xsyevd/**",
  "/cuSPARSE/bicgstab/**",
  "/.deepsource.toml",
  "/LICENSE.TXT",
  "/README.md",
  "/.gitignore",
  "/.gitmodules",
  "/cuSPARSE/gpsvInterleavedBatch/**",
  "/cuSOLVER/gesvdjBatched/**",
  "/cuSOLVER/syevdx/**",
  "/cuSPARSE/dense2sparse_blockedell/**",
  "/nvJPEG/Image-Resize/input_images/**",
  "/cuBLAS/Level-2/hemv/**",
  "/cuRAND/cmake/**",
  "/NPP/findContour/images/**",
  "/cuRAND/Host/sobol64/**",
  "/cuBLAS/Level-2/tpmv/**",
  "/cuFFT/1d_mgpu_c2c/**",
  "/cuFFTMp/Fortran_samples/c2c/**",
  "/MathDx/cuFFTDx/helloworld/**",
  "/cuRAND/Host/scrambled_sobol32/**",
  "/cuBLAS/Extensions/tpttr/**",
  "/nvJPEG2000/nvJPEG2000-Decoder-Pipelined/**",
  "/cuBLAS/Level-2/gbmv/**",
  "/cuSOLVER/potrfBatched/**",
  "/cuBLAS/Level-2/tbsv/**",
  "/cuTENSOR/CMakeLists.txt",
  "/cuTENSOR/reduction.cu",
  "/cuTENSOR/contraction_autotuning.cu",
  "/cuTENSOR/contraction_simple.cu",
  "/cuTENSOR/contraction_plan_cache.cu",
  "/cuTENSOR/README.md",
  "/cuTENSOR/einsum.cu",
  "/cuTENSOR/elementwise_permute.cu",
  "/cuTENSOR/elementwise_trinary.cu",
  "/cuTENSOR/contraction.cu",
  "/cuTENSOR/Makefile",
  "/cuTENSOR/elementwise_binary.cu",
  "/cuBLASLt/LtIgemmTensor/**",
  "/cuSOLVER/sygvj/**",
  "/nvTIFF/README.md",
  "/nvJPEG2000/nvJPEG2000-Decoder/images/4k_image_lossy/**",
  "/cuFFTMp/samples/c2c/**",
  "/cuFFTMp/README.md",
  "/nvJPEG/Image-Resize-WaterMark/CMakeLists.txt",
  "/nvJPEG/Image-Resize-WaterMark/img9wm.png",
  "/nvJPEG/Image-Resize-WaterMark/NVLogo.png",
  "/nvJPEG/Image-Resize-WaterMark/imageResizeWatermark.cpp",
  "/nvJPEG/Image-Resize-WaterMark/imageResizeWatermark.h",
  "/nvJPEG/Image-Resize-WaterMark/README.md",
  "/nvJPEG/Image-Resize-WaterMark/img9.png",
  "/nvJPEG/Image-Resize-WaterMark/NVLogo.jpg",
  "/cuBLAS/Level-3/her2k/**",
  "/cuSPARSE/spsv_csr/**",
  "/cuSPARSE/spvv/**",
  "/cuSOLVER/orgqr/**",
  "/MathDx/cuFFTDx/convolution/**",
  "/cuBLAS/Level-2/hpr2/**",
  "/cuSOLVER/Xgeqrf/**",
  "/cuRAND/Host/scrambled_sobol64/**",
  "/cuSOLVERMp/**",
  "/cuSPARSE/spmv_coo/**",
  "/cuSOLVER/csrqr/**",
  "/cuBLAS/Extensions/GemmEx/**",
  "/nvTIFF/nvTIFF-Python-Example/nvtiff_test.py",
  "/nvTIFF/nvTIFF-Python-Example/bali_notiles.tif",
  "/nvTIFF/nvTIFF-Python-Example/README.md",
  "/nvJPEG/Image-Resize-WaterMark/input_images/**",
  "/cuSPARSE/spsm_csr/**",
  "/cuBLAS/Level-2/trsv/**",
  "/cuFFTMp/JAX_FFT/Dockerfile",
  "/cuFFTMp/JAX_FFT/pyproject.toml",
  "/cuFFTMp/JAX_FFT/setup.py",
  "/cuFFTMp/JAX_FFT/README.md",
  "/nvJPEG/nvJPEG-Decoder-Backend-ROI/input_images/**",
  "/cuBLAS/Level-2/hpr/**",
  "/cuTENSOR/python/MANIFEST.in",
  "/cuTENSOR/python/setup.py",
  "/cuTENSOR/python/README.md",
  "/cuTENSOR/python/einsum.h",
  "/NPP/README.md",
  "/nvJPEG2000/nvJPEG2000-Encoder/CMakeLists.txt",
  "/nvJPEG2000/nvJPEG2000-Encoder/nvjpeg2k_encode.h",
  "/nvJPEG2000/nvJPEG2000-Encoder/README.md",
  "/nvJPEG2000/nvJPEG2000-Encoder/nvjpeg2k_encode.cpp",
  "/cuFFTMp/Fortran_samples/common.mk",
  "/cuSOLVER/syevjBatched/**",
  "/NPP/batchedLabelMarkersAndCompression/images/**",
  "/cuBLAS/Extensions/RotEx/**",
  "/cuBLAS/Extensions/GemmBatchedEx/**",
  "/cuBLASLt/LtFp8Matmul/**",
  "/cuSPARSELt/matmul_advanced/**",
  "/cuBLAS/utils/**",
  "/cuBLAS/Extensions/Csyrk3mEx/**",
  "/cuFFTMp/Fortran_samples/Fortran_wrappers_nvhpc/**",
  "/cuBLAS/Extensions/trttp/**",
  "/cuFFTMp/samples/common/**",
  "/cuSPARSE/simple_bench.sh",
  "/cuSPARSE/README.md",
  "/cuBLAS/Extensions/CsyrkEx/**",
  "/cuBLAS/Level-1/swap/**",
  "/nvJPEG2000/README.md",
  "/nvJPEG/nvJPEG-Decoder/input_images/**",
  "/cuFFT/3d_c2c/**",
  "/nvJPEG/nvJPEG-Decoder/nvjpegDecoder.cpp",
  "/nvJPEG/nvJPEG-Decoder/CMakeLists.txt",
  "/nvJPEG/nvJPEG-Decoder/README.md",
  "/nvJPEG/nvJPEG-Decoder/nvjpegDecoder.h",
  "/cuBLAS/Extensions/DotEx/**",
  "/cuBLAS/Extensions/CherkEx/**",
  "/cuRAND/Host/mrg32k3a/**",
  "/cuSPARSELt/README.md",
  "/cuBLAS/Level-1/copy/**",
  "/cuSPARSE/spmm_coo_batched/**",
  "/cuBLAS/Level-3/herk/**",
  "/nvJPEG/Image-Resize/CMakeLists.txt",
  "/nvJPEG/Image-Resize/imageResize.cpp",
  "/nvJPEG/Image-Resize/imageResize.h",
  "/nvJPEG/Image-Resize/README.md",
  "/cuBLAS/Level-3/trsmBatched/**",
  "/cuBLAS/Level-2/spmv/**",
  "/cuSOLVER/ormqr/**",
  "/cuSPARSE/sparse2dense_csr/**",
  "/nvJPEG/nvJPEG-Decoder-MultipleInstances/**",
  "/cuRAND/utils/**",
  "/cuBLAS/Extensions/geam/**",
  "/cuSOLVER/Xgesvd/**",
  "/cuBLAS/Level-3/gemmStridedBatched/**",
  "/cuBLAS/Level-2/syr2/**",
  "/cuFFTMp/samples/r2c_c2r/**",
  "/cuSPARSE/spsv_coo/**",
  "/cuBLAS/Extensions/dgmm/**",
  "/cuFFTMp/Fortran_samples/reshape/**",
  "/MathDx/cuFFTDx/README.md",
  "/cuBLAS/Extensions/AxpyEx/**",
  "/cuBLASLt/LtDgemmPresetAlgo/**",
  "/cuBLASLt/LtPlanarComplex/**",
  "/cuBLAS/Extensions/Nrm2Ex/**",
  "/cuFFTMp/Fortran_samples/r2c_c2r_pencils/**",
  "/cuSOLVER/MgSyevd/**",
  "/cuFFT/1d_c2c/**",
  "/cuSPARSE/axpby/**",
  "/cuRAND/Host/xorwow/**",
  "/cuSPARSE/graph_capture/**",
  "/NPP/watershedSegmentation/images/**",
  "/nvJPEG2000/nvJPEG2000-Decoder/nvjpeg2000DecodeSample.cpp",
  "/nvJPEG2000/nvJPEG2000-Decoder/CMakeLists.txt",
  "/nvJPEG2000/nvJPEG2000-Decoder/README.md",
  "/nvJPEG2000/nvJPEG2000-Decoder/nvjpeg2000DecodeSample.h",
  "/cuFFTMp/samples/r2c_c2r_no_descriptors/**",
  "/cuBLAS/Level-1/nrm2/**",
  "/cuBLAS/Level-2/spr/**",
  "/cuBLAS/Level-3/gemm3m/**",
  "/cuBLASLt/LtSgemmSimpleAutoTuning/**",
  "/nvJPEG2000/nvJPEG2000-Encoder/images/**",
  "/cuFFT/3d_mgpu_r2c_c2r/**",
  "/cuFFT/README.md",
  "/cuSPARSE/coosort/**",
  "/cuRAND/README.md",
  "/cuRAND/.gitignore",
  "/cuSPARSE/cg/**",
  "/cuBLAS/Level-3/syr2k/**",
  "/cuSOLVER/Xgesvdp/**",
  "/nvJPEG2000/nvJPEG2000-Decoder/images/2k_image_lossless/**",
  "/cuSPARSE/spmm_coo/**",
  "/cuBLAS/Level-3/syrkx/**",
  "/cuSOLVER/gesv/**",
  "/MathDx/cuFFTDx/fft_3d/**",
  "/NPP/findContour/CircuitBoard_Contours_8Way_2048x1024_8u.jpg",
  "/NPP/findContour/CircuitBoard_ContoursReconstructed_8Way_2048x1024_8u.jpg",
  "/NPP/findContour/CMakeLists.txt",
  "/NPP/findContour/CircuitBoard_CompressedMarkerLabelsUF_8Way_2048x1024_32u.jpg",
  "/NPP/findContour/contour_info.log",
  "/NPP/findContour/CircuitBoard_LabelMarkersUF_8Way_2048x1024_32u.jpg",
  "/NPP/findContour/findContour.cpp",
  "/NPP/findContour/CircuitBoard_2048x1024_8u.jpg",
  "/NPP/findContour/README.md",
  "/cuFFTMp/JAX_FFT/src/xfft/**",
  "/cuSPARSE/dense2sparse_csr/**",
  "/cuBLAS/cmake/**",
  "/cuSPARSE/spgemm_alg2/**",
  "/cuSOLVER/README.md",
  "/nvTIFF/nvTIFF-Decode-Encode/images/**",
  "/cuBLAS/Extensions/GemmStridedBatchedEx/**",
  "/cuSOLVER/Xgesvdr/**",
  "/cuBLAS/Level-3/hemm/**",
  "/cuSPARSE/compression/**",
  "/cuSPARSE/sddmm_csr/**",
  "/cuSOLVER/gesvdaStridedBatched/**",
  "/nvTIFF/nvTIFF-Python-Example/nvTIFF-Python-Whl/**",
  "/cuSOLVER/Xtrtri/**",
  "/cuSOLVER/sygvd/**",
  "/NPP/distanceTransform/images/**",
  "/cuBLAS/Level-1/asum/**",
  "/cuSOLVER/Xpotrf/**",
  "/cuBLAS/Level-3/gemmBatched/**",
  "/cuBLAS/Extensions/Cherk3mEx/**",
  "/cuFFTMp/JAX_FFT/src/cufftmp_jax/CMakeLists.txt",
  "/cuFFTMp/JAX_FFT/src/cufftmp_jax/cufftmp_jax.py",
  "/cuFFTMp/JAX_FFT/src/cufftmp_jax/__init__.py",
  "/cuFFTMp/JAX_FFT/src/cufftmp_jax/NOTICE",
  "/cuBLAS/Level-3/herkx/**",
  "/cuSPARSE/rot/**",
  "/cuFFTMp/samples/reshape/**",
  "/cuTENSORMg/**",
  "/cuRAND/Host/mtgp32/**",
  "/cuFFTMp/JAX_FFT/src/fft_common/**",
  "/cuFFT/3d_mgpu_c2c/**",
  "/cuSPARSE/spgemm/**",
  "/cuSPARSE/spmm_csr_batched/**",
  "/cuFFTMp/samples/r2c_c2r_pencils/**",
  "/cuBLAS/Level-2/symv/**",
  "/cuBLAS/Level-1/amin/**",
  "/cuBLAS/Level-2/gemv/**",
  "/cuBLAS/Level-3/syrk/**",
  "/cuBLAS/Level-1/rotm/**",
  "/cuFFT/utils/**",
  "/cuFFT/1d_r2c/**",
  "/cuSPARSE/spgemm_mem/**",
  "/cuFFTMp/JAX_FFT/src/cufftmp_jax/lib/**",
  "/cuBLASLt/Common/**",
  "/cuBLAS/Level-2/her2/**",
  "/cuSOLVER/MgPotrf/**",
  "/MathDx/README.md",
  "/cuFFTMp/samples/c2c_pencils/**",
  "/cuSPARSE/spmm_blockedell/**",
  "/cuTENSOR/python/cutensor/tensorflow/**",
  "/cuSOLVER/utils/**",
  "/cuFFT/2d_c2r/**",
  "/nvJPEG2000/nvJPEG2000-Decoder/images/2k_image_lossy/**",
  "/cuFFTMp/Fortran_samples/r2c_c2r_shared_scratch/**",
  "/cuSOLVER/Xgetrf/**",
  "/cuSOLVER/Xsyevdx/**",
  "/cuSPARSELt/matmul_minimal/**",
  "/cuFFTMp/samples/r2c_c2r_shared_scratch/**",
  "/cuBLAS/Level-2/tbmv/**",
  "/cuRAND/Host/mt19937/**",
  "/cuBLAS/Level-1/rotg/**"
]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "cxx"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "black"

[[transformers]]
name = "autopep8"