version = 1

exclude_patterns = [
  "cuSPARSE/spmv_csr/**",
  "cuBLASLt/LtSgemmCustomFind/**",
  "cuBLAS/Level-3/herk/**",
  "cuFFT/utils/**",
  "cuSPARSELt/matmul_advanced/**",
  "nvJPEG2000/nvJPEG2000-Decoder-Tile-Partial/**",
  "cuSOLVER/Xgesvdr/**",
  "cuFFTMp/samples/c2c_no_descriptors/**",
  "nvJPEG2000/README.md",
  "cuFFTMp/samples/common.mk",
  "cuSPARSE/spmm_coo_batched/**",
  "cuSOLVER/Xgesvdp/**",
  "cuFFT/3d_mgpu_r2c_c2r/**",
  "cuBLAS/Level-1/rot/**",
  "cuBLASLt/LtPlanarComplex/**",
  "cuBLAS/Extensions/Csyrk3mEx/**",
  "cuTENSOR/CMakeLists.txt",
  "cuTENSOR/reduction.cu",
  "cuTENSOR/contraction_autotuning.cu",
  "cuTENSOR/contraction_simple.cu",
  "cuTENSOR/contraction_plan_cache.cu",
  "cuTENSOR/README.md",
  "cuTENSOR/einsum.cu",
  "cuTENSOR/elementwise_permute.cu",
  "cuTENSOR/elementwise_trinary.cu",
  "cuTENSOR/contraction.cu",
  "cuTENSOR/Makefile",
  "cuTENSOR/elementwise_binary.cu",
  "cuSOLVER/Xsyevd/**",
  "cuFFTMp/JAX_FFT/src/xfft/**",
  "cuBLAS/Level-1/rotg/**",
  "cuBLAS/Level-3/trmm/**",
  "cuSOLVER/MgSyevd/**",
  "cuRAND/Host/mrg32k3a/**",
  "cuFFTMp/samples/r2c_c2r_shared_scratch/**",
  "nvJPEG2000/nvJPEG2000-Decoder/images/2k_image_lossy/**",
  "cuTENSORMg/**",
  "nvTIFF/nvTIFF-Python-Example/nvTIFF-Python-Whl/**",
  "cuBLASLt/LtHSHgemmStridedBatchSimple/**",
  "cuSPARSE/spsv_coo/**",
  "cuBLAS/Level-2/tpmv/**",
  "cuBLAS/README.md",
  "cuFFTMp/samples/c2c_pencils/**",
  "MathDx/cuFFTDx/helloworld/**",
  "nvJPEG/Image-Resize/CMakeLists.txt",
  "nvJPEG/Image-Resize/imageResize.cpp",
  "nvJPEG/Image-Resize/imageResize.h",
  "nvJPEG/Image-Resize/README.md",
  "NPP/watershedSegmentation/watershedSegmentation.cpp",
  "NPP/watershedSegmentation/CMakeLists.txt",
  "NPP/watershedSegmentation/README.md",
  "NPP/watershedSegmentation/watershedSegmentation.h",
  "cuBLAS/Level-1/dot/**",
  "cuSOLVER/orgqr/**",
  "cuSPARSE/simple_bench.sh",
  "cuSPARSE/README.md",
  "cuBLAS/Extensions/Cherk3mEx/**",
  "cuSOLVER/gesvdj/**",
  "cuFFTMp/samples/iterators/**",
  "cuSPARSELt/matmul_minimal/**",
  "cuSOLVER/Xpotrf/**",
  "cuFFTMp/Fortran_samples/r2c_c2r_shared_scratch/**",
  "cuBLASLt/LtIgemmTensor/**",
  "nvJPEG/nvJPEG-Decoder/input_images/**",
  "cuSPARSE/sparse2dense_csr/**",
  "cuBLAS/Level-2/her2/**",
  "cuBLAS/Level-3/hemm/**",
  "cuBLAS/Level-3/symm/**",
  "cuRAND/Host/mtgp32/**",
  "MathDx/cuFFTDx/fft_3d/**",
  "NPP/findContour/CircuitBoard_Contours_8Way_2048x1024_8u.jpg",
  "NPP/findContour/CircuitBoard_ContoursReconstructed_8Way_2048x1024_8u.jpg",
  "NPP/findContour/CMakeLists.txt",
  "NPP/findContour/CircuitBoard_CompressedMarkerLabelsUF_8Way_2048x1024_32u.jpg",
  "NPP/findContour/contour_info.log",
  "NPP/findContour/CircuitBoard_LabelMarkersUF_8Way_2048x1024_32u.jpg",
  "NPP/findContour/findContour.cpp",
  "NPP/findContour/CircuitBoard_2048x1024_8u.jpg",
  "NPP/findContour/README.md",
  "cuBLAS/Level-1/nrm2/**",
  "NPP/batchedLabelMarkersAndCompression/images/**",
  "cuFFTMp/JAX_FFT/src/cufftmp_jax/CMakeLists.txt",
  "cuFFTMp/JAX_FFT/src/cufftmp_jax/cufftmp_jax.py",
  "cuFFTMp/JAX_FFT/src/cufftmp_jax/__init__.py",
  "cuFFTMp/JAX_FFT/src/cufftmp_jax/NOTICE",
  "MathDx/cuFFTDx/fft_2d/**",
  "cuSPARSE/spvv/**",
  "cuFFTMp/README.md",
  "cuRAND/Host/xorwow/**",
  "nvJPEG/Image-Resize-WaterMark/CMakeLists.txt",
  "nvJPEG/Image-Resize-WaterMark/img9wm.png",
  "nvJPEG/Image-Resize-WaterMark/NVLogo.png",
  "nvJPEG/Image-Resize-WaterMark/imageResizeWatermark.cpp",
  "nvJPEG/Image-Resize-WaterMark/imageResizeWatermark.h",
  "nvJPEG/Image-Resize-WaterMark/README.md",
  "nvJPEG/Image-Resize-WaterMark/img9.png",
  "nvJPEG/Image-Resize-WaterMark/NVLogo.jpg",
  "cuBLAS/Level-3/gemm/**",
  "cuBLAS/Level-2/tbmv/**",
  "cuRAND/utils/**",
  "cuRAND/Host/scrambled_sobol32/**",
  "cuBLAS/Level-2/hemv/**",
  "nvJPEG/nvJPEG-Decoder-MultipleInstances/**",
  "cuBLAS/Level-2/trmv/**",
  "cuSOLVER/syevjBatched/**",
  "cuBLASLt/LtDgemmPresetAlgo/**",
  "cuBLAS/Level-2/her/**",
  "cuBLAS/Level-3/trsmBatched/**",
  "cuBLASLt/LtSgemm/**",
  "cuBLAS/Level-1/asum/**",
  "cuSOLVERMp/**",
  "cuTENSOR/python/MANIFEST.in",
  "cuTENSOR/python/setup.py",
  "cuTENSOR/python/README.md",
  "cuTENSOR/python/einsum.h",
  "cuFFTMp/Fortran_samples/r2c_c2r_pencils/**",
  "cuSOLVER/utils/**",
  "cuBLAS/Extensions/RotEx/**",
  "cuSOLVER/cmake/**",
  "cuSPARSE/scatter/**",
  "cuSOLVER/gesv/**",
  "cuBLAS/Level-1/amin/**",
  "cuFFTMp/Fortran_samples/c2c/**",
  "cuSOLVER/Xgesvd/**",
  "cuFFTMp/samples/common/**",
  "cuBLAS/Level-3/syrkx/**",
  "cuBLAS/Level-2/hpmv/**",
  "cuFFT/3d_c2c/**",
  "NPP/watershedSegmentation/images/**",
  "cuBLAS/Level-3/gemmBatched/**",
  "cuSPARSE/spgemm_alg2/**",
  "cuSPARSELt/matmul_minimal_playground/**",
  "cuBLAS/Level-2/hbmv/**",
  "cuSOLVER/syevdx/**",
  "cuSOLVER/Xtrtri/**",
  "cuBLAS/Level-2/syr2/**",
  "NPP/README.md",
  "cuSPARSE/coosort/**",
  "cuFFTMp/JAX_FFT/tests/**",
  "cuBLAS/Extensions/CsyrkEx/**",
  "cuSPARSE/spsm_coo/**",
  "nvTIFF/README.md",
  "cuBLAS/Extensions/Nrm2Ex/**",
  "cuTENSOR/python/cutensor/c_extensions.py",
  "cuTENSOR/python/cutensor/package_info.py",
  "cuTENSOR/python/cutensor/__init__.py",
  "cuTENSOR/python/cutensor/c_extensions_utils.py",
  "cuTENSOR/python/cutensor/common.py",
  "nvJPEG/Image-Resize/input_images/**",
  "cuFFT/lto_ea/CMakeLists.txt",
  "cuFFT/lto_ea/README.md",
  "cuFFT/lto_ea/Makefile",
  "cuSOLVER/Xsyevdx/**",
  "cuFFT/1d_mgpu_c2c/**",
  "cuSPARSE/axpby/**",
  "cuFFTMp/Fortran_samples/Fortran_wrappers_nvhpc/**",
  "nvTIFF/nvTIFF-GeoTIFF-Decode/images/**",
  "cuSPARSE/bicgstab/**",
  "cuRAND/Host/philox/**",
  "cuRAND/Host/mt19937/**",
  "MathDx/cuFFTDx/README.md",
  "cuSOLVER/getrf/**",
  "cuBLAS/Level-2/symv/**",
  "cuFFT/2d_c2r/**",
  "cuBLAS/Level-3/trsm/**",
  "cuBLAS/Level-2/trsv/**",
  "cuBLAS/Level-2/hpr/**",
  "cuFFT/3d_mgpu_c2c/**",
  "cuBLAS/Level-2/gemv/**",
  "cuBLAS/Extensions/ScalEx/**",
  "MathDx/cuFFTDx/utils/**",
  "cuFFTMp/JAX_FFT/Dockerfile",
  "cuFFTMp/JAX_FFT/pyproject.toml",
  "cuFFTMp/JAX_FFT/setup.py",
  "cuFFTMp/JAX_FFT/README.md",
  "cuBLAS/Level-3/syrk/**",
  "cuSPARSE/sddmm_csr_batched/**",
  "cuSOLVER/ormqr/**",
  "cuTENSOR/python/cutensor/torch/**",
  "cuFFTMp/samples/r2c_c2r_pencils/**",
  "cuFFTMp/Fortran_samples/c2c_pencils/**",
  "cuBLASLt/CMakeLists.txt",
  "cuBLASLt/README.md",
  "cuFFTMp/samples/r2c_c2r_no_descriptors/**",
  "cuBLAS/Level-2/tpsv/**",
  "cuBLASLt/LtFp8Matmul/**",
  "cuBLAS/Extensions/AxpyEx/**",
  "cuBLAS/Level-2/spr2/**",
  "NPP/distanceTransform/images/**",
  ".deepsource.toml",
  "LICENSE.TXT",
  "README.md",
  ".gitignore",
  ".gitmodules",
  "cuBLAS/Extensions/geam/**",
  "cuFFTMp/extra_bootstraps/**",
  "cuBLAS/Level-1/rotm/**",
  "cuFFT/lto_ea/src/**",
  "cuBLAS/cmake/**",
  "cuSPARSE/gpsvInterleavedBatch/**",
  "cuSPARSE/spmm_blockedell/**",
  "cuRAND/cmake/**",
  "cuBLAS/Extensions/dgmm/**",
  "cuSOLVER/MgPotrf/**",
  "nvJPEG/Image-Resize-WaterMark/input_images/**",
  "cuBLAS/Level-2/hpr2/**",
  "cuBLASLt/Common/**",
  "cuBLAS/Level-2/ger/**",
  "cuBLAS/Level-2/syr/**",
  "NPP/distanceTransform/CMakeLists.txt",
  "NPP/distanceTransform/README.md",
  "NPP/distanceTransform/distanceTransform.cpp",
  "NPP/distanceTransform/DistanceTransformTrue_Dolphin1_319x319_16u.jpg",
  "NPP/distanceTransform/dolphin1_Input_319x319_8u.jpg",
  "cuBLAS/Extensions/GemmBatchedEx/**",
  "nvTIFF/nvTIFF-Decode-Encode/images/**",
  "cuSPARSE/spmm_coo/**",
  "cuSPARSE/rot/**",
  "nvTIFF/nvTIFF-Decode-Encode/CMakeLists.txt",
  "nvTIFF/nvTIFF-Decode-Encode/README.md",
  "nvTIFF/nvTIFF-Decode-Encode/getopt.h",
  "nvTIFF/nvTIFF-Decode-Encode/nvtiff_example.cu",
  "cuFFTMp/JAX_FFT/src/fft_common/**",
  "cuFFTMp/JAX_FFT/misc/**",
  "cuBLAS/utils/**",
  "cuFFTMp/samples/c2c/**",
  "cuSPARSE/spsm_csr/**",
  "cuSOLVER/csrqr/**",
  "cuSPARSE/spgemm_mem/**",
  "cuBLAS/Level-1/copy/**",
  "cuSPARSE/spmv_coo/**",
  "cuSPARSE/spmm_csr_batched/**",
  "cuSOLVER/gesvdaStridedBatched/**",
  "cuBLAS/Extensions/DotEx/**",
  "cuBLAS/Level-3/gemmStridedBatched/**",
  "cuFFTMp/Fortran_samples/r2c_c2r/**",
  "nvJPEG/nvJPEG-Decoder-Backend-ROI/CMakeLists.txt",
  "nvJPEG/nvJPEG-Decoder-Backend-ROI/nvJPEGROIDecode.cpp",
  "nvJPEG/nvJPEG-Decoder-Backend-ROI/nvJPEGROIDecode.h",
  "nvJPEG/nvJPEG-Decoder-Backend-ROI/img9_roi.png",
  "nvJPEG/nvJPEG-Decoder-Backend-ROI/README.md",
  "nvJPEG/nvJPEG-Decoder-Backend-ROI/threadpool.h",
  "cuSPARSE/sddmm_csr/**",
  "cuFFT/README.md",
  "cuSOLVER/sygvdx/**",
  "cuBLAS/Level-1/swap/**",
  "MathDx/cuFFTDx/block_fft/**",
  "cuBLAS/Level-2/gbmv/**",
  "nvJPEG2000/nvJPEG2000-Encoder/images/**",
  "cuFFT/1d_c2c/**",
  "cuBLAS/Extensions/trttp/**",
  "cuSOLVER/MgGetrf/**",
  "nvJPEG2000/nvJPEG2000-Decoder/nvjpeg2000DecodeSample.cpp",
  "nvJPEG2000/nvJPEG2000-Decoder/CMakeLists.txt",
  "nvJPEG2000/nvJPEG2000-Decoder/README.md",
  "nvJPEG2000/nvJPEG2000-Decoder/nvjpeg2000DecodeSample.h",
  "cuSOLVER/sygvj/**",
  "nvJPEG/README.md",
  "cuBLAS/Extensions/CherkEx/**",
  "cuFFTMp/Fortran_samples/r2c_c2r_no_descriptors/**",
  "cuBLAS/Level-3/syr2k/**",
  "cuSPARSE/gather/**",
  "cuBLAS/Level-3/gemm3m/**",
  "NPP/batchedLabelMarkersAndCompression/CMakeLists.txt",
  "NPP/batchedLabelMarkersAndCompression/batchedLabelMarkersAndCompression.h",
  "NPP/batchedLabelMarkersAndCompression/batchedLabelMarkersAndCompression.cpp",
  "NPP/batchedLabelMarkersAndCompression/README.md",
  "NPP/batchedLabelMarkersAndCompression/dirent.h",
  "cuBLAS/Level-2/spr/**",
  "nvJPEG/nvJPEG-Decoder/nvjpegDecoder.cpp",
  "nvJPEG/nvJPEG-Decoder/CMakeLists.txt",
  "nvJPEG/nvJPEG-Decoder/README.md",
  "nvJPEG/nvJPEG-Decoder/nvjpegDecoder.h",
  "cuFFTMp/Fortran_samples/reshape/**",
  "cuBLAS/Level-1/axpy/**",
  "cuRAND/README.md",
  "cuRAND/.gitignore",
  "cuSPARSELt/matmul/**",
  "cuBLAS/Level-2/spmv/**",
  "cuRAND/Host/scrambled_sobol64/**",
  "cuBLAS/Level-2/tbsv/**",
  "cuFFTMp/samples/r2c_c2r/**",
  "MathDx/cuFFTDx/convolution/**",
  "cuFFTMp/Fortran_samples/c2c_no_descriptors/**",
  "cuSPARSE/cg/**",
  "cuBLAS/Level-1/rotmg/**",
  "nvJPEG2000/nvJPEG2000-Decoder-Pipelined/**",
  "nvJPEG2000/nvJPEG2000-Decoder/images/4k_image_lossy/**",
  "cuBLAS/Extensions/GemmEx/**",
  "nvTIFF/nvTIFF-Python-Example/nvtiff_test.py",
  "nvTIFF/nvTIFF-Python-Example/bali_notiles.tif",
  "nvTIFF/nvTIFF-Python-Example/README.md",
  "nvJPEG2000/nvJPEG2000-Decoder/images/2k_image_lossless/**",
  "cuSOLVER/README.md",
  "cuBLAS/Level-3/herkx/**",
  "cuRAND/Host/sobol32/**",
  "cuBLAS/Extensions/GemmStridedBatchedEx/**",
  "cuBLAS/Level-2/sbmv/**",
  "nvJPEG/nvJPEG-Decoder-Backend-ROI/input_images/**",
  "cuSOLVER/potrfBatched/**",
  "cuSPARSE/dense2sparse_blockedell/**",
  "cuSOLVER/Xgeqrf/**",
  "cuTENSOR/python/cutensor/tensorflow/**",
  "cuFFTMp/Fortran_samples/common.mk",
  "cuSOLVER/Xgetrf/**",
  "MathDx/README.md",
  "cuRAND/Host/sobol64/**",
  "cuSPARSE/spmm_csr/**",
  "cuBLAS/Level-3/her2k/**",
  "cuBLAS/Level-1/scal/**",
  "NPP/findContour/images/**",
  "cuBLAS/Level-1/amax/**",
  "cuFFTMp/samples/reshape/**",
  "cuSPARSE/spmm_csr_op/**",
  "nvJPEG2000/nvJPEG2000-Encoder/CMakeLists.txt",
  "nvJPEG2000/nvJPEG2000-Encoder/nvjpeg2k_encode.h",
  "nvJPEG2000/nvJPEG2000-Encoder/README.md",
  "nvJPEG2000/nvJPEG2000-Encoder/nvjpeg2k_encode.cpp",
  "cuSOLVER/gesvdjBatched/**",
  "nvTIFF/nvTIFF-GeoTIFF-Decode/CMakeLists.txt",
  "nvTIFF/nvTIFF-GeoTIFF-Decode/README.md",
  "nvTIFF/nvTIFF-GeoTIFF-Decode/getopt.h",
  "nvTIFF/nvTIFF-GeoTIFF-Decode/nvtiff_geotiff_decode.cpp",
  "cuSPARSE/compression/**",
  "cuSOLVER/sygvd/**",
  "cuSOLVER/syevj/**",
  "cuSOLVER/syevd/**",
  "cuBLASLt/LtSgemmSimpleAutoTuning/**",
  "cuFFT/1d_r2c/**",
  "cuSPARSE/graph_capture/**",
  "cuFFTMp/JAX_FFT/src/cufftmp_jax/lib/**",
  "cuSPARSELt/README.md",
  "cuSPARSE/dense2sparse_csr/**",
  "cuBLAS/Extensions/tpttr/**",
  "cuSOLVER/gesvd/**",
  "cuSPARSE/spsv_csr/**",
  "cuSPARSE/spgemm/**"
]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "cxx"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "black"